# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf8XbZM62QarhejmjDTAiP5WFrOEfqau
"""

#Calculadora

num1   = 0
num2   = 0
resultado = 0
op     = ''

while True:
  num1 = float(input('Digite o primeiro número: '))
  op   = input('Digite a operação: ')
  num2 = float(input('Digite o segundo número: '))

  if    op == '+' :
    resultado = num1 + num2
  elif  op == '-' :
    resultado = num1 - num2
  elif  op == '*' :
    resultado = num1 * num2
  elif  op == '/' :
    resultado = num1 / num2
  else:
    print("Operação incorreta")


  print('O resultado é: ' ,resultado)

